// Code generated by "stringer -type=Format"; DO NOT EDIT.

package instructions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatR-0]
	_ = x[FormatI-1]
	_ = x[FormatS-2]
	_ = x[FormatB-3]
	_ = x[FormatU-4]
	_ = x[FormatJ-5]
}

const _Format_name = "FormatRFormatIFormatSFormatBFormatUFormatJ"

var _Format_index = [...]uint8{0, 7, 14, 21, 28, 35, 42}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
